"""LLM exposure auditor — a curation aid that re-reads an anchorage's prose and
judges its `exposed_sectors`, separate from extraction.

It uses the same Anthropic structured tool-use pattern as `extract.py`, but its job
is to *check* an existing record rather than create one. Calibration note: its
**flags have good recall** (it catches over-reach the `confidence` field misses), but
its **suggested sectors are a starting point, not truth** — it can still invert
"protection from X" into exposure. Treat output as a worklist for a human, and refine
`_AUDIT_INSTRUCTIONS` as new misread patterns surface.
"""

from __future__ import annotations

from pilotbook_mcp.models import Anchorage

_8POINT = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]

_AUDIT_INSTRUCTIONS = """You audit one anchorage's wind/swell EXPOSURE against its pilot-book prose.
`exposed_sectors` = the 8-point compass directions the anchorage is OPEN TO — wind or swell FROM
those directions makes it uncomfortable. Protected directions are NOT listed.

Judge whether the CURRENT exposed_sectors match the prose. Rules (these are where past audits went wrong):
- "protection/shelter from X" -> X is PROTECTED (NOT exposed).
- "little/no/limited protection from X" -> X IS exposed (negation — read it carefully).
- "good in all but X" / "all but X winds" -> exposed to X only.
- "some shelter from X tucked behind <feature>" -> generally still exposed to X (conditional lee).
- A direction named only as an anchoring location ("anchor along the SE shore", "depths off the NE shore")
  is NOT an exposure — ignore it.
- The prose often describes OTHER nearby/overflow/sub-anchorages — judge ONLY the named anchorage; ignore the others.
- Empty exposed_sectors is CORRECT when the anchorage is fully enclosed / protected from all directions,
  or when discomfort comes from current/eddies/boat-wake rather than wind.
- Only mark disagree when the prose CLEARLY contradicts the list. If the prose is silent on exposure, AGREE — do not invent.
Call audit_exposure with your verdict."""

AUDIT_TOOL = {
    "name": "audit_exposure",
    "description": "Report whether the listed exposed_sectors match the anchorage's prose.",
    "input_schema": {
        "type": "object",
        "properties": {
            "agree": {"type": "boolean",
                      "description": "true if the current exposed_sectors are correct per the prose"},
            "suggested_sectors": {"type": "array", "items": {"type": "string", "enum": _8POINT},
                                  "description": "corrected sectors (only if agree=false); empty list = fully protected"},
            "audit_confidence": {"type": "string", "enum": ["high", "medium", "low"]},
            "reason": {"type": "string", "description": "one sentence citing the prose"},
        },
        "required": ["agree", "audit_confidence", "reason"],
    },
    "cache_control": {"type": "ephemeral"},
}


def build_audit_prompt() -> list[dict]:
    """System blocks (cached — identical across every record)."""
    return [{"type": "text", "text": _AUDIT_INSTRUCTIONS, "cache_control": {"type": "ephemeral"}}]


def audit_record(anchorage: Anchorage, *, client, model: str = "claude-sonnet-4-6") -> dict | None:
    """Ask the model whether `anchorage.exposed_sectors` matches its prose.

    Returns the tool input dict ({agree, suggested_sectors?, audit_confidence, reason})
    or None if no verdict came back.
    """
    user = (f"Anchorage: {anchorage.name}\n"
            f"Current exposed_sectors: {anchorage.exposed_sectors}\n\n"
            f"Prose:\n{anchorage.prose}")
    resp = client.messages.create(
        model=model,
        max_tokens=600,
        system=build_audit_prompt(),
        tools=[AUDIT_TOOL],
        tool_choice={"type": "tool", "name": "audit_exposure"},
        messages=[{"role": "user", "content": user}],
    )
    for block in resp.content:
        if getattr(block, "type", None) == "tool_use" and getattr(block, "name", None) == "audit_exposure":
            return dict(block.input)
    return None


def format_worklist(source: str, flagged: list[dict]) -> str:
    """Render the auditor's disagreements as a triage markdown table."""
    order = {"high": 0, "medium": 1, "low": 2}
    rows = sorted(flagged, key=lambda r: order.get(r.get("audit_confidence"), 3))
    lines = [
        f"# Exposure audit — {source}",
        "",
        "Auto-generated by `pilotbook audit`. The auditor's **flags** have real recall, but its "
        "**suggested sectors are a starting point, not truth** — verify each against the prose before "
        "applying. Empty suggestion = fully protected.",
        "",
        f"{len(flagged)} flagged.",
        "",
        "| audit | anchorage | current | suggested | why |",
        "|-------|-----------|---------|-----------|-----|",
    ]
    for r in rows:
        cur = r.get("current") or []
        sug = r.get("suggested")
        sug = "—" if sug is None else (sug or "[] (fully protected)")
        reason = (r.get("reason") or "").replace("|", "\\|")
        lines.append(f"| {r.get('audit_confidence','?')} | {r.get('name','?')} | "
                     f"{cur} | {sug} | {reason} |")
    lines.append("")
    return "\n".join(lines)
